import { readFileSync } from "fs";
import path from "path";
import type { VerificationResult } from "@/components/wallet/VerificationResultView";

export interface InActionStep {
  step_title: string;
  narration: string;
  result: VerificationResult;
}

/**
 * Precomputed walkthrough of the Phase 2 three-actor loop — a frozen
 * snapshot generated by examples/generate_in_action_content.py, not a live
 * fetch. Static export has no guaranteed running `service/` for a visitor;
 * this is Phase 2's already-tested code path, not a new computation.
 */
export function getInActionSteps(): InActionStep[] {
  const raw = readFileSync(path.join(process.cwd(), "content", "in_action.json"), "utf-8");
  const parsed = JSON.parse(raw) as { walkthroughs: InActionStep[] };
  return parsed.walkthroughs;
}
