import Link from "next/link";
import { getAnchorSwap, getWalletEval, getWalletRedteam, OUTCOME_COLUMNS } from "@/lib/results";
import { RatesChart } from "@/components/results/RatesChart";
import { ESSAYS } from "@/lib/essays";

export const metadata = { title: "Takeaway — eIDAS Wallet & QES Lab" };

const ACCEPT_SHADES = ["", "bg-[var(--accept)]/10", "bg-[var(--accept)]/20", "bg-[var(--accept)]/30"];
const ACCENT_SHADES = ["", "bg-[var(--accent-c)]/10", "bg-[var(--accent-c)]/20", "bg-[var(--accent-c)]/30"];

const DEFECT_REPEATS_NOTE = "4 repeats each, 8 genuine";

function shadeIndex(count: number): number {
  if (count === 0) return 0;
  if (count < 4) return 1;
  if (count < 8) return 2;
  return 3;
}

function cellClass(column: string, count: number): string {
  const shades = column === "accept" ? ACCEPT_SHADES : ACCENT_SHADES;
  return shades[shadeIndex(count)];
}

export default function TakeawayPage() {
  const evalResult = getWalletEval();
  const redteam = getWalletRedteam();
  const anchorSwap = getAnchorSwap();

  const species = Object.keys(evalResult.matrix);
  const { summary } = evalResult;

  return (
    <div className="max-w-4xl mx-auto px-6 py-12 space-y-14">
      <div>
        <h1
          className="text-3xl font-bold tracking-tight"
          style={{ fontFamily: "var(--font-display)", color: "var(--foreground)" }}
        >
          Takeaway
        </h1>
        <p className="text-sm text-[var(--text-2)] mt-2 max-w-2xl">
          The eval: {evalResult.corpus_size}{" "}
          labelled presentations across the taxonomy&apos;s 13 defect
          species, scored by the real verifier —
          not a mock. Every number below is read live from{" "}
          <code className="font-mono text-xs px-1 py-0.5 rounded bg-[var(--surface-2)]">
            results/wallet_eval.json
          </code>
          , generated by{" "}
          <code className="font-mono text-xs px-1 py-0.5 rounded bg-[var(--surface-2)]">
            examples/run_eval.py
          </code>
          .
        </p>
      </div>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold" style={{ fontFamily: "var(--font-display)" }}>
          Confusion matrix
        </h2>
        <p className="text-sm text-[var(--text-2)] max-w-2xl">
          Rows are defect species (seed {evalResult.seed}, {DEFECT_REPEATS_NOTE}
          ). Columns are the eight ordered checks plus{" "}
          <code className="font-mono text-xs">accept</code> — the check a
          presentation is caught at, or that it clears all eight. Shade depth
          tracks count, not correctness judgement; every non-zero cell here
          is the species landing exactly where its label says it should.
        </p>
        <div className="overflow-x-auto rounded-xl border border-[var(--border-c)]">
          <table className="text-xs w-full border-collapse">
            <thead>
              <tr className="bg-[var(--surface-2)]">
                <th className="text-left font-mono px-3 py-2 text-[var(--text-2)] sticky left-0 bg-[var(--surface-2)]">
                  species
                </th>
                {OUTCOME_COLUMNS.map((col) => (
                  <th key={col} className="text-right font-mono px-2 py-2 text-[var(--text-2)] whitespace-nowrap">
                    {col}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {species.map((sp) => (
                <tr key={sp} className="border-t border-[var(--border-c)]">
                  <td className="font-mono px-3 py-1.5 text-[var(--foreground)] sticky left-0 bg-[var(--surface)] whitespace-nowrap">
                    {sp}
                  </td>
                  {OUTCOME_COLUMNS.map((col) => {
                    const count = evalResult.matrix[sp][col] ?? 0;
                    return (
                      <td key={col} className={`text-right font-mono px-2 py-1.5 ${cellClass(col, count)}`}>
                        {count || ""}
                      </td>
                    );
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold" style={{ fontFamily: "var(--font-display)" }}>
          Summary rates
        </h2>
        <p className="text-sm text-[var(--text-2)] max-w-2xl">
          APCER over the 8 crypto/protocol + trust-chain species (
          {summary.apcer_species.join(", ")}), BPCER over{" "}
          <code className="font-mono text-xs">genuine</code>, and the
          wrong-check rate (right decision, wrong reason) over everything.
          All three are 0 — no cryptographic or protocol defect got past the
          verifier, and no genuine presentation got rejected.
        </p>
        <RatesChart
          data={[
            { label: "APCER — crypto/trust", value: summary.apcer ?? 0, color: "reject" },
            { label: "BPCER — genuine", value: summary.bpcer ?? 0, color: "reject" },
            { label: "wrong-check rate", value: summary.wrong_check_rate, color: "reject" },
          ]}
        />
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold" style={{ fontFamily: "var(--font-display)" }}>
          AI red-team: crypto vs. policy
        </h2>
        <p className="text-sm text-[var(--text-2)] max-w-2xl">
          The flagship finding. A heuristic agent ({redteam.agent}) ran{" "}
          {redteam.n_attempts} attempts, two aimed at the crypto/protocol
          checks and two at the policy layer. Crypto: 0% success — nothing
          bluffs a digest or a signature. Policy: 50% success — withholding{" "}
          <code className="font-mono text-xs">birth_date</code> while
          disclosing only <code className="font-mono text-xs">age_over_18</code>{" "}
          defeats the consistency check by construction, not by exploiting a
          bug. Selective disclosure is the credential&apos;s intended
          feature; it also removes the verifier&apos;s ability to
          cross-check. eIDAS makes the trust core AI-proof and pushes
          residual fraud risk into the policy layer the bank owns.
        </p>
        <RatesChart
          data={[
            { label: "crypto family", value: redteam.by_check_family.crypto.success_rate, color: "accept" },
            { label: "policy family", value: redteam.by_check_family.policy.success_rate, color: "reject" },
          ]}
        />
        <div className="overflow-x-auto rounded-xl border border-[var(--border-c)]">
          <table className="text-xs w-full border-collapse">
            <thead>
              <tr className="bg-[var(--surface-2)]">
                <th className="text-left font-mono px-3 py-2 text-[var(--text-2)]">attempt</th>
                <th className="text-left font-mono px-3 py-2 text-[var(--text-2)]">family</th>
                <th className="text-left font-mono px-3 py-2 text-[var(--text-2)]">strategy</th>
                <th className="text-left font-mono px-3 py-2 text-[var(--text-2)]">outcome</th>
              </tr>
            </thead>
            <tbody>
              {redteam.attempts.map((a) => (
                <tr key={a.attempt_id} className="border-t border-[var(--border-c)] align-top">
                  <td className="font-mono px-3 py-2 text-[var(--foreground)] whitespace-nowrap">{a.attempt_id}</td>
                  <td className="font-mono px-3 py-2 text-[var(--text-2)] whitespace-nowrap">
                    {a.targeted_check_family}
                  </td>
                  <td className="px-3 py-2 text-[var(--text-2)]">{a.strategy}</td>
                  <td className="px-3 py-2">
                    <span
                      className={`font-mono px-1.5 py-0.5 rounded-full text-[10px] ${
                        a.accepted
                          ? "bg-[var(--reject-zone)] text-[var(--reject)]"
                          : "bg-[var(--accept-zone)] text-[var(--accept)]"
                      }`}
                    >
                      {a.accepted ? "accepted — hole found" : "rejected"}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold" style={{ fontFamily: "var(--font-display)" }}>
          Trust-anchor swap: EU vs. UK DIATF
        </h2>
        <p className="text-sm text-[var(--text-2)] max-w-2xl">
          Same verifier, same 56-item corpus, only the{" "}
          <code className="font-mono text-xs">TrustAnchorProvider</code>{" "}
          implementation differs. For an issuer both frameworks recognize,
          the two postures are operationally indistinguishable — every
          decision matches; only the anchor provenance differs.
        </p>
        <div className="grid grid-cols-3 gap-3">
          <div className="rounded-xl border border-[var(--border-c)] bg-[var(--surface)] p-4">
            <div className="text-2xl font-bold font-mono text-[var(--foreground)]">
              {anchorSwap.mutual_recognition.total_items}
            </div>
            <div className="text-xs text-[var(--text-2)] mt-1">items compared</div>
          </div>
          <div className="rounded-xl border border-[var(--border-c)] bg-[var(--surface)] p-4">
            <div className="text-2xl font-bold font-mono text-[var(--accept)]">
              {anchorSwap.mutual_recognition.decision_mismatches}
            </div>
            <div className="text-xs text-[var(--text-2)] mt-1">decision mismatches</div>
          </div>
          <div className="rounded-xl border border-[var(--border-c)] bg-[var(--surface)] p-4">
            <div className="text-2xl font-bold font-mono text-[var(--foreground)]">
              {anchorSwap.mutual_recognition.items_with_differing_anchor_id}
            </div>
            <div className="text-xs text-[var(--text-2)] mt-1">differing anchor_id only</div>
          </div>
        </div>
        <p className="text-sm text-[var(--text-2)] max-w-2xl pt-1">
          The real divergence needs a deliberately constructed scenario: an
          issuer registered only in the EU provider, absent from UK-DIATF.
        </p>
        <div className="rounded-xl border border-[var(--border-c)] overflow-hidden">
          <table className="text-xs w-full border-collapse">
            <thead>
              <tr className="bg-[var(--surface-2)]">
                <th className="text-left font-mono px-3 py-2 text-[var(--text-2)]">posture</th>
                <th className="text-left font-mono px-3 py-2 text-[var(--text-2)]">decision</th>
                <th className="text-left font-mono px-3 py-2 text-[var(--text-2)]">failing checks</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-t border-[var(--border-c)]">
                <td className="font-mono px-3 py-2 text-[var(--foreground)]">EU trusted list</td>
                <td className="px-3 py-2">
                  <span className="font-mono px-1.5 py-0.5 rounded-full text-[10px] bg-[var(--accept-zone)] text-[var(--accept)]">
                    {anchorSwap.eu_only_issuer_scenario.eu_decision}
                  </span>
                </td>
                <td className="px-3 py-2 text-[var(--text-2)] font-mono">—</td>
              </tr>
              <tr className="border-t border-[var(--border-c)] bg-[var(--reject-zone)]/30">
                <td className="font-mono px-3 py-2 text-[var(--foreground)]">UK DIATF/DVS</td>
                <td className="px-3 py-2">
                  <span className="font-mono px-1.5 py-0.5 rounded-full text-[10px] bg-[var(--reject-zone)] text-[var(--reject)]">
                    {anchorSwap.eu_only_issuer_scenario.uk_decision}
                  </span>
                </td>
                <td className="px-3 py-2 text-[var(--text-2)] font-mono">
                  {anchorSwap.eu_only_issuer_scenario.uk_failing_checks.join(", ")}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="text-sm text-[var(--text-2)] max-w-2xl">
          A bank running both postures needs two separate registration/
          trust-resolution processes, not a config flag — the tier mapping
          onto <code className="font-mono text-xs">PID</code> is a modeling
          simplification (DIATF has no PID/QEAA/EAA categories of its own);
          the real distinction lives in <code className="font-mono text-xs">anchor_id</code>{" "}
          and framework, not in the schema. See{" "}
          <code className="font-mono text-xs">docs/TWO_POSTURE.md</code>.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-lg font-semibold" style={{ fontFamily: "var(--font-display)" }}>
          Key learnings
        </h2>
        <div className="space-y-4 max-w-2xl text-sm text-[var(--text-2)]">
          <p>
            <b className="text-[var(--foreground)]">Valid signature, trusted issuer and live credential are three
            separate questions, not one.</b> A verifier that collapses them — that treats a passing signature check
            as proof of accreditation, or accreditation as proof the credential hasn&apos;t since been revoked —
            has a real gap even though every individual check it runs is correct. Six of the thirteen defect
            species in this eval exist purely to test that a verifier keeps these separate; APCER is 0 across all
            of them, but only because the checks are ordered and none is allowed to stand in for another.
          </p>
          <p>
            <b className="text-[var(--foreground)]">The crypto core is AI-unbluffable; the policy layer isn&apos;t —
            and selective disclosure is why.</b> The flagship finding: a red-team agent scored 0% against
            signatures, digests and key-binding, and 50% against the policy layer, by withholding{" "}
            <code className="font-mono text-xs">birth_date</code> while disclosing only{" "}
            <code className="font-mono text-xs">age_over_18</code>. That isn&apos;t a bug in selective disclosure —
            it&apos;s the credential doing exactly what it was designed to do, which is also exactly what removes
            the verifier&apos;s ability to cross-check a derived claim against its source. A bank writing its own
            attestation schemas inherits this trade-off on day one, not as an edge case discovered in production.
          </p>
          <p>
            <b className="text-[var(--foreground)]">A verifier is its configuration as much as its code.</b> Seven
            of the thirteen species live entirely in the verifier&apos;s trust list, registration scope or status
            entries — an otherwise perfect presentation, rejected only because this deployment&apos;s config says
            so. The confusion matrix has to be re-run against a bank&apos;s actual configuration, not assumed from
            a vendor&apos;s reference deployment.
          </p>
          <p>
            <b className="text-[var(--foreground)]">UK and EU are two trust postures, not one with a flag.</b> The
            anchor swap (above) shows the mutual-recognition case is boring — same verifier, same decisions, only
            the anchor label differs — which is exactly why the EU-only-issuer case matters: a bank running both
            regimes needs two real registration and trust-resolution processes, because DIATF and eIDAS 2.0 solve
            the same problem with trust anchors that don&apos;t currently talk to each other.
          </p>
          <p>
            <b className="text-[var(--foreground)]">A browser wallet teaches the protocol; it can&apos;t clear the
            certification bar.</b> The PWA holds a genuine non-extractable key, gates release behind a
            real WebAuthn gesture, and completes a real cross-device presentation — none of it faked — and still
            isn&apos;t a Wallet Unit, because the ARF&apos;s bar is a certified WSCD plus a Wallet Unit Attestation,
            not a software promise about key export. See{" "}
            <Link href="/experiment" className="underline">
              the attestation wall
            </Link>
            .
          </p>
        </div>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold" style={{ fontFamily: "var(--font-display)" }}>
          Essays
        </h2>
        <div className="grid grid-cols-1 gap-3">
          {ESSAYS.map((essay) => (
            <Link
              key={essay.slug}
              href={`/essays/${essay.slug}`}
              className="rounded-xl border border-[var(--border-c)] bg-[var(--surface)] p-4 hover:border-[var(--accent-c)] transition-colors"
            >
              <div className="text-sm font-semibold text-[var(--foreground)]">{essay.title}</div>
              <div className="text-xs text-[var(--text-2)] mt-1">{essay.dek}</div>
            </Link>
          ))}
        </div>
      </section>
    </div>
  );
}
